### ISSUE TITLE
Support for frozen index paks

### ISSUE THREAD

**Issue by BrandonItaly** [4sval/FModel#237]
### Description

Support for loading frozen index paks would be a very useful feature as the Steam version of Dead by Daylight is switching to this pak format in the next update. The Epic Games Store and Microsoft Store versions of the game are already using this pak format and are unable to be loaded using FModel.

**Comment by xploree** [comment]
just heat it up

**Comment by GMatrixGames** [comment]
Frozen-Index paks are already supported in the latest commit of CUE4Parse, so it'll be included in the next release (stable/beta) of FModel

**Comment by BrandonItaly** [comment]
The assets do not load properly with the latest commit of CUE4Parse. Already tested it

**Comment by GMatrixGames** [comment]
Then please provide more information including a latest log.

**Comment by BrandonItaly** [comment]
This is the error message when loading most assets. 
`[ERR] One or more errors occurred. (Bad state (unknown compression method (0xC1))) at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)`
[FModel-Log-2022-01-04.txt](https://github.com/iAmAsval/FModel/files/7811769/FModel-Log-2022-01-04.txt)

**Comment by GMatrixGames** [comment]
This is not an effect of a frozen index I don't believe. Are you aware of what compression they're using since clearly ZLib isn't it.

**Comment by BrandonItaly** [comment]
I'm pretty sure that the paks use frozen index and are able to be unpacked perfectly fine with UnrealPak. [This forum](https://www.gildor.org/smf/index.php?topic=3129.60) says that the game uses frozen index too.

**Comment by BrandonItaly** [comment]
I'm not sure of what compression they are using

**Comment by BrandonItaly** [comment]
Just checked and the paks do look like they are using Zlib, so I have no idea of what else could be wrong. Would it be useful if I provided a pak file for the game?

**Comment by Amrsatrio** [comment]
We will try further with RL Sideswipe iOS paks. The work with frozen index paks apparently isn't fully done yet.

**Comment by GMatrixGames** [comment]
This has been fixed.
