### ISSUE TITLE
[Updated] Patch 5.7.0 and updated Unreal Engine 4.25 to 4.27, don't load the models and meshes

### ISSUE THREAD

**Issue by Th3Nigh7mare** [4sval/FModel#267]
### Game

Dead by Daylight

### Error

```shell
No error appears in the console, it just doesn't load the models in its version of unreal engine 4.27! However, loading models and meshes has always worked with the version 4.25 of the live version.
```

### Reproduction steps

1. Open a model or a mesh and the following error appears in the interface: No material found in the mesh and the model display does not load
![error](https://user-images.githubusercontent.com/66384195/161824215-251e4bf8-80f9-4a10-aecd-7dfa070ad0d4.PNG)
.

**Comment by Th3Nigh7mare** [comment]
I will add today another image, the 5.7.0 today was launch!
![Error](https://user-images.githubusercontent.com/66384195/165562472-87b06d9c-8acc-4368-a865-8212cbf4a7d3.PNG)


On discord, I used this setting but it doesn't seem to work even so.
![settings](https://user-images.githubusercontent.com/66384195/165562530-cb706d2c-70d9-408f-a807-038b545cccca.PNG)

**Comment by iAmAsval** [comment]
Are you sure the game now runs on 4.27?
Did you try one version above / below ?

**Comment by donovanj44** [comment]
It is 4.27

**Comment by Th3Nigh7mare** [comment]
> Are you sure the game now runs on 4.27? Did you try one version above / below ?

Hi Asval! yeah its 4.27! I have tried to modify this:

`if (Ar.Game is >= EGame.GAME_UE5_0 or EGame.GAME_UE4_25_Plus or EGame.GAME_UE4_27)`
and work! I don't know if in future versions you will be able to patch it, without affecting Fornite and other games!

**Comment by 4sval** [comment]
fixed in next release
