### ISSUE TITLE
Does not Read Pak files for KH3

### ISSUE THREAD

**Issue by narknon** [4sval/FModel#293]
### Game

Kingdom Hearts III

### Error

```shell
FModel will not load KHIII paks.  Console states "[ERR] An encrypted archive has been found. In order to decrypt it, please specify a working AES encryption key" even with the correct AES key.  Further, I have entered AES keys for other games and they have worked so I am not entering the key incorrectly.
```

### Reproduction steps

Select KH3 pak directory and enter the AES key.

**Comment by 4sval** [comment]
the aes key format is hexadecimal, if not, it won't work

**Comment by narknon** [comment]
Does that mean the AES needs to be converted to hex, or that games that don't use hex won't work?
