### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by amqteras** [4sval/FModel#296]
### Game

Fortnite

### Error

```shell
[ERR] Index was outside the bounds of the array.
      at CUE4Parse.MappingsProvider.UsmapParser.Parse(FArchive Ar)
[ERR] Mappings could not get pulled, extracting packages might not work properly. If so, press F12 or please restart.
```

### Reproduction steps

1. Start Fmodel
2.Load Archives
3. Error occurs

Perhaps this will cause
No material found in the mesh" when previewing any of the mesh data

I don't speak English.
I am writing this text by translation, so I apologize if there is something wrong in the explanation

![スクリーンショット 2022-06-23 150856](https://user-images.githubusercontent.com/108049421/175227743-1ab266e5-843d-464d-aa2c-48bdab6c38b2.png)
.

**Comment by 4sval** [comment]
F12

**Comment by 4sval** [comment]
it's literally written...

**Comment by amqteras** [comment]
> delete `Output/.data/++Fortnite+Release-21.10-CL-20756627-Windows_oo.usmap` and press F12

Thanks for the reply.

I just tried this.
I can confirm it works fine!

Thank you very much.
