### ISSUE TITLE
unable to extract mesh file 

### ISSUE THREAD

**Issue by xalteropsx** [4sval/FModel#298]
### Game

blade and soul 

### Error

```shell
unable to extract 
[ERR] Object reference not set to an instance of an object.
      at CUE4Parse_Conversion.Meshes.MeshConverter.TryConvert(USkeletalMesh originalMesh, CSkeletalMesh& convertedMesh)
```

### Reproduction steps

while extracting file

**Comment by xalteropsx** [comment]
![Screenshot_264](https://user-images.githubusercontent.com/103671642/175966560-80b8feb3-2481-47fe-af23-b0ed8bbf6e3d.png)

**Comment by 4sval** [comment]
https://github.com/4sval/FModel/issues/291#issuecomment-1158883200
