### ISSUE TITLE
Unable to preview any .uasset file. Done everything I have seen, don't know what else to do

### ISSUE THREAD

**Issue by nerd0ne** [4sval/FModel#300]
### Game

Fortnite

### Error

```shell
[ERR] One or more errors occurred. (Found IoStore Package but global data is missing, can't serialize)
      at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

(PS. I have reset AES multiple times and used F12, don't know what else to do)
```

### Reproduction steps

1. Went to any .uasset file.
2. Doubled clicked to preview.
3. Error occurred and said, "Failed".

**Comment by nerd0ne** [comment]
As stated, I have reset AES key and used F12. Can't find anything else to do.

**Comment by nerd0ne** [comment]
I have also have the latest Fmodel version.

**Comment by 4sval** [comment]
repair your game

**Comment by nerd0ne** [comment]
I am very new to this sorry.
