### ISSUE TITLE
Bug Title

### ISSUE THREAD

**Issue by GameDev111333** [4sval/FModel#309]
### Game

Fortnite

### Error

```shell
Why update this program if you can't export Fortnite game files now?

As I understand it, with the release of a new version of the program, the export problem has not been solved?

[ERR] Mappings could not get pulled, extracting packages might not work properly. If so, either press F12, restart, or come back later.
```

### Reproduction steps

Loadin Mode: All

**Comment by GameDev111333** [comment]
https://github.com/GMatrixGames  There will be no fixed file export?

**Comment by GameDev111333** [comment]
@GMatrixGames There will be no fixed file export?

**Comment by 4sval** [comment]
> Why update this program if you can't export Fortnite game files now?

because there are other games???

**Comment by GMatrixGames** [comment]
This is an UNREAL ENGINE file explorer, not a FORTNITE file explorer.

**Comment by GameDev111333** [comment]
Is everything difficult with Fortnite or will you ever try to fix it?

**Comment by GhostScissors** [comment]
It's not a FModel side issue

**Comment by GameDev111333** [comment]
Are animations and models exported from other games?

**Comment by 4sval** [comment]
please join discord kthx
