### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by GameDev111333** [4sval/FModel#313]
### Description

Hello!

If you have a previously downloaded archive with Fortnite animations (the Emotes folder). 

Please upload this content to the hosting for download. 
Thanks!

**Comment by GameDev111333** [comment]
@FabianFG 
Closing the topic without an answer. 
Great job!

**Comment by nerd0ne** [comment]
> @FabianFG Closing the topic without an answer. Great job!

this has nothing to do with a suggestion nor a bug report for fmodel
