### ISSUE TITLE
.pak exporting problem

### ISSUE THREAD

**Issue by jicomy** [4sval/FModel#315]
### Game

Life Is Strange: True Colors (PS4)

### Error

```shell
when im trying to export or view a content, it will fail!
files that packed in .pak file will be just null bytes (0x00), but the thing is that arhcive is uncompressed, so there must be a problem that files inside paks will be export as null files

sample file: [DOWNLOAD](https://filebin.net/e9054g8zynkbyo54/dlc_preorderoutfitssiren-ps4.7z) [1.25 mb]
```

### Reproduction steps

1- Open a folder that contain .pak file
2- choose a folder within opened pak file and select a file
3- export files that i selected
4- open exported files on my hard drive with hex editor and see that files are filed just with null blocks

**Comment by 4sval** [comment]
your archive is clearly broken
