### ISSUE TITLE
Show Properties by default instead of generated(?) image

### ISSUE THREAD

**Issue by sgtfrankieboy** [4sval/FModel#320]
### Description

I'm trying to use FModel to look at the Properties of certain uasset files from MultiVersus. However FModel shows an image when I open them (for example `Character_Velma.uasset`). I have to right click the tab and do "View Properties".

I would like to have an option to disable the generated image and just show the properties, or somehow show both?

**Comment by 4sval** [comment]
https://github.com/4sval/FModel/wiki/Getting-Started#property

*Each tab is cut in half between the text area and the image area, both resizable.*

**Comment by sgtfrankieboy** [comment]
Whoops. Got it, the generated image was so big the entire Properties section was gone.

**Comment by 4sval** [comment]
yes, if the tab has never been resized, the image will take the lead
that's the downside of `GridLength.Auto`
