### ISSUE TITLE
Display Fortnite Save the World llama "PackImage" in the preview

### ISSUE THREAD

**Issue by PRO100KatYT** [4sval/FModel#321]
### Description

Currently FModel displays the `LargePreviewImage` asset when double clicking on a CardPack item. Every CardPack that is a Llama is lacking the `PackImage` asset on them.

Here's what it **currently** looks like on one of the llamas:
![image](https://user-images.githubusercontent.com/67335438/189527169-379053a5-9965-4a49-95cb-5e1b6b72911a.png)

Here's what is **should** look like on one of the llamas:
![image](https://user-images.githubusercontent.com/67335438/189527374-8dca8df3-b8f9-4597-b4b7-e5df788ecfec.png)

Make sure to not apply the `PackImage` to the Mini Reward Llama CardPack image since it shouldn't have one.

**Comment by 4sval** [comment]
FModel takes textures as is.
`PackImage` is a mask image supposed to be put somewhere over `LargePreviewImage` only when `bIsLlama` is true and `LootTierGroup` is not CardPack_Basic.
I guess it could be fixed if we hardcode the size and position but it seems like a lot of code changes to me for only 19 packages and such a slight difference.
