### ISSUE TITLE
export folder's packages raw data

### ISSUE THREAD

**Issue by cui-yang** [4sval/FModel#324]
### Description

**Special thanks to your FModel. When I was extracting the pakchunk0.ucas file, the extraction speed was getting slower and slower due to the large number of files. Is it possible to speed up the extraction speed by increasing the number of processes? I hope I can understand the English. ,thank you very much.**

**Comment by 4sval** [comment]
clear the logs, use cue4parse, or just don't do this
why do you need to export a whole folder to a point you can notice it goes slower and slower?
