### ISSUE TITLE
Tower of Fantasy - Can't open anything

### ISSUE THREAD

**Issue by shimizu-izumi** [4sval/FModel#327]
### Game

Tower of Fantasy

### Error

```shell
Loading the game:
[ERR] CUE4Parse.UE4.Exceptions.ParserException: Invalid FString length '1375731712'
   at CUE4Parse.UE4.Readers.FArchive.ReadFString()
[WRN] Could not load localized resources in 'English', language may not exist
[ERR] Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: �. Path '', line 1, position 7.
   at Newtonsoft.Json.JsonTextReader.ParseValue()

Trying to open an asset file:
[ERR] CUE4Parse.UE4.Exceptions.ParserException: Invalid uasset magic: 0xA6BE0DEE != 0x9E2A83C1
   at CUE4Parse.UE4.Objects.UObject.FPackageFileSummary..ctor(FArchive Ar)
```

### Reproduction steps

1. Use FModel to load Tower of Fantasy and add the AES Key like for any other game
2. Try to open something, "text files" can be opened but aren't readable

Extra info:
This error is most likely caused due to changes in Tower of Fantasy's encryption that came with the 2.0 update

**Comment by GMatrixGames** [comment]
Build [this](https://github.com/4sval/FModel/tree/snooper) branch from source or wait for a new update. If that does not work, please create a ticket in our discord for easier tracking.

**Comment by Amrsatrio** [comment]
I built this earlier myself and it works with the latest update.
https://cdn.discordapp.com/attachments/741522145112227960/1032543918614659112/publish.7z
