### ISSUE TITLE
Odd incorrect Y axis

### ISSUE THREAD

**Issue by speaker-60** [4sval/FModel#329]
### Game

FF7 First Soldier 4.25

### Error

```shell
Firstly i dont know if this is or isnt a bug on fmodels part, just reporting as one incase it is.

I was using Fmodel to look at uMaps to get the position cords for meshes so i can recreate some maps in blender(tried using the blender addon, but dosnt work for this game)

Here is a mesh according to what the umap says in Fmodel
https://cdn.discordapp.com/attachments/736560503035527209/1037824397626593300/image.png
Can see on the right the loaded umap in fmodel, and the static mesh listed. Its the same mesh i have selected in blender. Its not positioned right as yu can see there clipping through eachother

These pieces snap together by eye so i can manually snap them together, not all models on a map are like this ofcorse
Here i corrected the position manually moving it into position
https://cdn.discordapp.com/attachments/736560503035527209/1037824259285856296/image.png
Z and X cords or correct as shown in the umap but the Y cord wasnt, so that the issue.
For some reason the y axis is not correct

I dont know if this is a bug with Fmodel or something else perhaps im missing something, hoping if its something im missing it can be pointed out so i can continue my project.
```

### Reproduction steps

Here is the umap file i used in my example image
https://cdn.discordapp.com/attachments/736560503035527209/1037824612697919498/MidgarCity_Landscape_x0y1ABC.umap
https://cdn.discordapp.com/attachments/736560503035527209/1037824612966338630/MidgarCity_Landscape_x0y1ABC.uexp
And here are the extracted pskx meshes for testing 
https://cdn.discordapp.com/attachments/736560503035527209/1037825030144413726/SM_MC_LandScape_x0y1A.pskx
https://cdn.discordapp.com/attachments/736560503035527209/1037825030710624387/SM_MC_LandScape_x0y1B.pskx
https://cdn.discordapp.com/attachments/736560503035527209/1037825029703991399/SM_MC_LandScape_x0y1C.pskx

Look at the umap positions and place the meshes in blender to replicate what i have in my screenshots

Let me know if you need more info or the actual pak file, just through the specific files would save time

**Comment by speaker-60** [comment]
Figured out the y axis is inverted so in my example image if i have y axis -32509.935 to 32509.925 Its now in the correct location
invert Y of other objects and they all snap in place. Easy enough fix my end 

No idea if this is a bug on fmodel or some special case with this game just reporting it incase

**Comment by 4sval** [comment]
It is how UE woks

**Comment by speaker-60** [comment]
Right i guess its a difference between blenders axis and unreals
