### ISSUE TITLE
Can't open FModel with out throwing an "Unhandled Exception Occurred" error. 

### ISSUE THREAD

**Issue by Gamilith** [4sval/FModel#330]
### Game

Sea of Thieves

### Error

```shell
An unhandled exception occurred: The invocation of the constructor on type 'FModel.MainWindow' that matches the specified binding constraints threw an exception
```

### Reproduction steps

I tried to open an asset folder and my pc froze so I closed Fmodel with task manager and now i'm completely unable to open it again.

**Comment by Gamilith** [comment]
log file explained nothing. how do i uninstall and reinstall?

**Comment by 4sval** [comment]
Just reset your settings

https://github.com/4sval/FModel/wiki/Settings-Explanation

**Comment by Gamilith** [comment]
There's nothing in that folder and it's still giving the same error. here's the log if that would help. 
[FModel-Log-2022-11-14.txt](https://github.com/4sval/FModel/files/10003746/FModel-Log-2022-11-14.txt)

**Comment by 4sval** [comment]
> log file explained nothing. how do i uninstall and reinstall?

log file explained everything in line 8

did you uninstall Fortnite by deleting its folder??
If so, that's not how you're supposed to do it.

Your `C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat` still references it so either fix the content of that file or uninstall games the way you install them, through their launcher

**Comment by Gamilith** [comment]
deleted the contents of the .dat file and it fixed everything. I uninstalled through the launcher but I guess it didn't update that file. Thanks for the help.
