### ISSUE TITLE
Unable to open load Asteria_Terrian.umap

### ISSUE THREAD

**Issue by Tekniqu3** [4sval/FModel#339]
### Game

Fortnite

### Error

```shell
Loading... Esc to cancle

[FModel] [INF] User DOUBLE-CLICKED to extract 'FortniteGame/Content/Athena/Asteria/Maps/Asteria_Terrain.umap'
[FModel] [ERR] Could not read InstancedStaticMeshComponent correctly
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CUE4Parse.UE4.Objects.Core.Math.FMatrix..ctor(FArchive Ar)
   at CUE4Parse.UE4.Assets.Exports.Component.StaticMesh.FInstancedStaticMeshInstanceData..ctor(FArchive Ar)
   at CUE4Parse.UE4.Assets.Exports.Component.StaticMesh.UInstancedStaticMeshComponent.<>c__DisplayClass2_0.<Deserialize>b__0()
   at CUE4Parse.UE4.Assets.Exports.Component.StaticMesh.UInstancedStaticMeshComponent.Deserialize(FAssetArchive Ar, Int64 validPos)
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize)
```

### Reproduction steps

1. Open model
2. Open (FortniteGame/Content/Athena/Asteria/Maps/Asteria_Terrain.umap)

I tried by turnned of preview model and Preview Levels (.umap) this i have same issue. Fmodel take too much ram and crashed and attached log file

[FModel-Log-2022-12-05.txt](https://github.com/4sval/FModel/files/10154115/FModel-Log-2022-12-05.txt)
![image](https://user-images.githubusercontent.com/96134900/205637385-209c4eaf-217c-4e1f-814c-1d5e8ab45610.png)

**Comment by 4sval** [comment]
![image](https://user-images.githubusercontent.com/26126862/205638570-86cbba85-52b3-4cf0-9c97-8f8e25f4a512.png)

**Comment by Tekniqu3** [comment]
Have you try to open it by double clicking? Is it not only for me? Here is the video.

https://drive.google.com/file/d/1sgjdYMQTtCwPar5MZUMNpvR7y__K4VCj/view?usp=share_link

**Comment by 4sval** [comment]
cue4parse / fmodel was not built to be able to extract HUGE packages
open smaller umaps, fmodel will never handle the whole fortnite map at once

**Comment by Tekniqu3** [comment]
Sorry to bother you again, I'm not trying to export. I just want to see the
json. I was able to see Artemis_Terrain.usmap before Chapter 4 update. I
was using FModel 4.3.

Thanks for your help and Thanks for FModel (It's really amazing, I am
learning a lot from FModel source ).

**Comment by GMatrixGames** [comment]
disable previewing umaps in your settings, and hope you have enough memory lol
