### ISSUE TITLE
Possible fixes for typefaces.cs

### ISSUE THREAD

**Issue by OperativeA115** [4sval/FModel#341]
Hey all usually I am a C++ / C programmer making these but here I am doing CSharp OOF
Well here they are hope it helps

1. Use appropriate and descriptive names for variables, methods, and classes. For example, instead of `_BURBANK_BIG_CONDENSED_BOLD`, you could use `burbankBigCondensedBoldFontUri`. This will make the code easier to read and understand.

2. Consider using an enum to represent the different font constants, rather than defining multiple constants for each font. This will reduce the amount of code and make it easier to manage the font constants.

3. Use meaningful comments to describe what the code is doing, especially for complex or non-obvious sections of code. This will help others who read the code to understand its purpose and how it works.

4. Avoid using hard-coded paths, such as `/Game/UI/Foundation/Fonts/`, and instead use properties or constants to store these values. This will make the code more flexible and easier to modify if the paths change.

5. Consider using a more modern way to load resources, such as using a dependency injection framework, rather than using the `pack://application:,,,/` URI scheme. This will make the code more maintainable and testable.

6. Consider using a more modern font rendering library, such as the .NET Core `System.Drawing.Common` namespace, instead of SkiaSharp. This will provide better performance and support for newer font formats.

If you want me to look at anymore code to review over LMK
__Thanks OperativeA115 - C++ / C Programmer__

**Comment by 4sval** [comment]
1. input the text `how can the {coding_language} code below be improved` over at https://chat.openai.com/chat
2. paste said code
3. paste the response in a bug report

output:
![image](https://user-images.githubusercontent.com/26126862/206053713-01458f83-37ee-4c6b-be1f-0f84aa359459.png)

I think we can make it out without you OperativeA115.

Kind Regards
