### ISSUE TITLE
.usmap files don't seem to save on a per game basis most of the time.

### ISSUE THREAD

**Issue by narknon** [4sval/FModel#343]
### Game

Any using .usmap files

### Error

```shell
No errors.
```

### Reproduction steps

1. Add a local .usmap file to a game in settings.
2. Change to any other game
3. .usmap file for first game persists in settings.
4. Swap it for the 2nd game's .usmap
5. Change back to first game
6. 2nd game's .usmap persists in settings.

**Comment by 4sval** [comment]
yes that's how it works with unknown games

**Comment by narknon** [comment]
So should it be a feature request to add saving per-game for that instead?

**Comment by 4sval** [comment]
no, it's a global change where we should get rid of FGame and refactor the user settings
but this fmodel has been built around FGame so it's pretty annoying to get rid of it and that's not a priority atm
