### ISSUE TITLE
Fortnite [LIVE] returns 401 (Unaurhorized) (FModel Beta 4.4.0.0)

### ISSUE THREAD

**Issue by archeruwu** [4sval/FModel#346]
### Game

Fortnite [LIVE]

### Error

```shell
Upon selecting Fortnite's live version, FModel cannot pull the live manifest due to a 401 request return.
```

### Reproduction steps

1. Under "Directory", Select "Selector"
2. Pick "Fortnite [LIVE]"
3. Restart FModel when it ask you to.
4. FModel will return a 401 request (Request failed, unauthorized)
![image](https://user-images.githubusercontent.com/18449883/208230717-fd9bd1de-cf29-47c7-aace-89bb10a13bc7.png)

**Comment by 4sval** [comment]
It's been fixed already
