### ISSUE TITLE
Project Melody crashes FModel on export

### ISSUE THREAD

**Issue by jkerman2000** [4sval/FModel#347]
### Game

Project Melody

### Error

```shell
No errors show up in the log file. The program just exits.
```

### Reproduction steps

Load the most recent version of Project Melody, using UE 5.1. Try double clicking on any mesh.

**Comment by GMatrixGames** [comment]
Do you have a link to this game?

**Comment by jkerman2000** [comment]
It's available through BigBangStudios' Patreon.

**Comment by GMatrixGames** [comment]
I'm not going to pay to get a hentai game, so if you can provide the game files, I can look into it.
