### ISSUE TITLE
Packing Multiple .PSA Animations Into One

### ISSUE THREAD

**Issue by b1naryTR** [4sval/FModel#352]
### Description

I couldn't find any way to mass-export animations from game Valorant. With this, I can use [Glidor's 3ds Max script](https://www.gildor.org/projects/unactorx) to animate some stuff. Thanks.

**Comment by b1naryTR** [comment]
I meant packing multiple animations into one .psa file. Sorry about not explaining it briefly.

**Comment by 4sval** [comment]
one .psa = one animation
I don't get it
