### ISSUE TITLE
Allow for skipping existing files that've been extracted.

### ISSUE THREAD

**Issue by PerryTute** [4sval/FModel#353]
I've been attempting to extract some larger titles, like "Ghostwire: Tokyo" and unfortunately due to how many (100,000+) loose files there are to sift through I've had FModel crash a few times, when extracting files, making my efforts frustratingly pointless.

**Comment by GMatrixGames** [comment]
Use CUE4Parse

**Comment by PerryTute** [comment]
> Use CUE4Parse

**Comment by PerryTute** [comment]
Clicked close by accident, can CUE4Parse actually extract the files of the archives its pointed at or is it only able to save the output to a .json?

**Comment by 4sval** [comment]
CUE4Parse can do what fmodel does and even more
