### ISSUE TITLE
Surpress bulk JSON export asking for save location on every file

### ISSUE THREAD

**Issue by FoobianBlock** [4sval/FModel#354]
### Description

**I would like to propose the JSON bulk export feature only asking you for a folder location once, and placing all JSON files in there.**

I previoulsy used a custom program to mass evaluate JSON files I could easily export from FModel by searching a folder, selecting all files of the search result, and double clicking one of them, followed by my whole selection getting exported with the auto-export feature. Now, with [that removed, and a new mass export feature added](https://github.com/4sval/FModel/commit/a7bc3d0b60f550f5d35d681a5849f574e5598f77), it asks for a path to export the JSON files to, which is a bit cumbersome when dealing with ~1500 files.

**Comment by 4sval** [comment]
if that were just me there would not be a single popup asking where to save files but this debate already happened and not everybody likes the idea

the removal of all auto exports was meant to tell people that fmodel should not be used to mass "do something here blindly"
as you said you're dealing with ~1500 files, thus you're one of the targets of the removal

if you want everything from a folder you can right-click the folder instead and it won't ask for a path on every file
if you're filtering the folder, it would be better to use [CUE4Parse](https://github.com/FabianFG/CUE4Parse) instead

**Comment by FoobianBlock** [comment]
Hm, I see. I'll use 4.4.0.0 for now and move my workflow over when I find time. Thank you for your quick response btw
