### ISSUE TITLE
Error with Midnight Suns models: System.NullReferenceException

### ISSUE THREAD

**Issue by jhamilton0** [4sval/FModel#355]
I'm working on a mod for Marvel's Midnight Suns, but when trying to open or export SkeletalMeshes, I'm getting the following error:

[ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at CUE4Parse_Conversion.Meshes.MeshConverter.TryConvert(USkeletalMesh originalMesh, CSkeletalMesh& convertedMesh)
   
The mesh properties load, but the model window doesn't open and trying to export a .psk doesn't do anything.

I am able to export the meshes using umodel.exe, although I think that program may be messing up the bone weights slightly, so I'd like to export them using FModel as well for comparison.

**Comment by 4sval** [comment]
use the correct ue version?

**Comment by jhamilton0** [comment]
Switching the "UE Versions" setting from "GAME_UE4_27" to "GAME_DAUNTLESS" seems to have fixed the problem. Thanks!

One follow-up question: it looks like both FModel and UE Model Viewer currently only support meshes with four skin weights per vertex, and discard the smaller weights when more than four are present. Unfortunately, this leads to a pretty bad issue with Midnight Suns- the models there are rigged with eight weights per vertex, and discarding the smaller ones causes clothing and hair clipping issues in animations. Are there any plans to update FModel with support for more skin weights in the future? Do you know of any alternatives that might be able to export models with all of the skin weights currently?

**Comment by 4sval** [comment]
there are plans to get rid of the actorx data format to allow easier implementation of new features and rework all the 10yo non-sense written into it

increased bone influence is included in this plan

I don't know any other alternatives as of now

**Comment by jhamilton0** [comment]
A note for anyone else experiencing the same problem: I was able to export an fbx with the correct skin weights by following the method at: https://www.gildor.org/smf/index.php/topic,7770.0.html - compiling a custom version of UEditor, using a modified version of the custom class posted there, and then exporting the uncooked asset from the editor.  The results are inconsistent, however- it worked for one model, but causes a crash with a different model.
