### ISSUE TITLE
Error openning Hogwarts Legacy static meshes

### ISSUE THREAD

**Issue by klukule** [4sval/FModel#357]
Openning any static mesh from Hogwarts Legacy (UE 4.27.2) will fail with following error:
```
[FModel] [ERR] Could not read StaticMesh correctly
CUE4Parse.UE4.Exceptions.ParserException: Invalid bool value (131071)
FAssetArchive Info: Engine/Content/BasicShapes/Cube.uasset Pos 8919 Length 9013
   at CUE4Parse.UE4.Assets.Exports.StaticMesh.UStaticMesh.Deserialize(FAssetArchive Ar, Int64 validPos)
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize)
   ```
   
The issue is seemingly caused by 64 byte chunk of data between loading of `FStaticMeshRenderData` and the Occluder data check
Skipping these 64 bytes results in the static mesh loading fine and can be exported... 

That chunk of data is always consistent across all static meshes and has following value (4x16 byte segments repeated):
`010000000000000001000000FFFFFFFF010000000000000001000000FFFFFFFF010000000000000001000000FFFFFFFF010000000000000001000000FFFFFFFF`

**Comment by 4sval** [comment]
can you upload one of the archives for us to try the fix

**Comment by klukule** [comment]
Sure,

here are two usset files, one is just the basic cube and other one is directly from game files - both are from the Hogwarts Legacy.

[Exports.zip](https://github.com/4sval/FModel/files/10690020/Exports.zip)

This is what works for me:
```csharp
            //...
            RenderData = new FStaticMeshRenderData(Ar, bCooked);

            if (Ar.Game == EGame.GAME_HogwartsLegacy)
            {
                Ar.ReadBytes(64);
            }

            if (bCooked && Ar.Game is >= EGame.GAME_UE4_20 and < EGame.GAME_UE5_0)
            //...
```

**Comment by NotOfficer** [comment]
Use `Position += 64` instead to not allocate those bytes.

**Comment by klukule** [comment]
I had that there originally, this is just leftover from when I was dumping those bytes so I could inspect (and post them).  And this is also a reason why I'm not opening pull request on either FModel or CUE4Parse, since this is my first proper look at the innerworkings of either and I don't know the code parctices etc... hence just the open issue.

**Comment by 4sval** [comment]
you can open one on CUE4Parse if you haven't found anything else that broke

there's no actual code practice yet, apart from not writing spaghettis

**Comment by klukule** [comment]
There are few texture names that need to be added into the whitelist for the 3D preview to load proper textures... but I'll make another pull request for that when I have all the names later down the line. - since it's not strictly necessary to allow proper functionality of the core features (i.e. static mesh exporting).

I'll be closing this issue since it's resolved and I'm gonna make pull request on CUE4Parse then.
