### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mobiuse** [4sval/FModel#358]
### Game

September 7th

### Error

```shell
[ERR] System.Exception: Program failed to link with error: Fragment info
-------------
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression

   at FModel.Views.Snooper.Shader..ctor(String name)
```

### Reproduction steps

open mesh

**Comment by 4sval** [comment]
missclick

**Comment by 4sval** [comment]
does it work on other games?

**Comment by Mobiuse** [comment]
did not check

**Comment by Mobiuse** [comment]
also with another game


[ERR] System.Exception: Program failed to link with error: Fragment info
-------------
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression

   at FModel.Views.Snooper.Shader..ctor(String name)

**Comment by 4sval** [comment]
what's your pc specs

**Comment by Mobiuse** [comment]
win10 64
cpu ntel(R) Core(TM) i5-3230M CPU @ 2.60GHz   2.60 GHz
ram 8
vid gforce 720

**Comment by Mobiuse** [comment]
it's in 3d view

An unhandled exception occurred: Program failed to link with error: Fragment info
-------------
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression
0(82) : error C5208: Sampler needs to be a uniform (global or parameter to main), need to inline function or resolve conditional expression

**Comment by Mobiuse** [comment]
do nothing about it?

**Comment by 4sval** [comment]
here are a few solutions you can try to fix it

- update your GPU drivers
- upgrade your GPU, it's been 9 years already...
- use [umodel](https://www.gildor.org/down/47/umodel/umodel_win32.zip)

**Comment by Mobiuse** [comment]
thanks for the quick replies and help, good luck
