### ISSUE TITLE
Gotham Knights

### ISSUE THREAD

**Issue by Phnxsmv** [4sval/FModel#360]
### Game

Gotham Knights

### Error

```shell
After the recent February patch the game's archives were turned into pak/ucas/utoc. Now there is a decompression error when trying to view/extract assets.

[ERR] System.IO.FileLoadException: Failed to decompress LZ4 data (Expected: 3045, Result: -1)
   at CUE4Parse.Compression.Compression.Decompress(Byte[] compressed, Int32 compressedOffset, Int32 compressedSize, Byte[] uncompressed, Int32 uncompressedOffset, Int32 uncompressedSize, CompressionMethod method, FArchive reader)
```

### Reproduction steps

1. Load GK archives in FModel
2. Double click assets or choose "Export raw data"

**Comment by 4sval** [comment]
use the correct ue version?

**Comment by Phnxsmv** [comment]
It worked fine before the recent patch. They changed the archive format to Io Store. Now it doesn't work anymore, even when setting the correct UE version.

**Comment by Amrsatrio** [comment]
Would be great if you can provide us with the smallest .pak + .utoc + .ucas pairs.

**Comment by Phnxsmv** [comment]
Oof, that's not possible, unfortunately. They packaged the whole game into just one pak/ucas/utoc. I'm sorry.

**Comment by Phnxsmv** [comment]
That is not the problem. The problem is utoc/ucas archive structure which also changes asset file format. But thanks for the tip.
