### ISSUE TITLE
Numerous open-source licensing violations

### ISSUE THREAD

**Issue by atenfyr** [4sval/FModel#367]
FModel relies on numerous projects (distributed as a part of FModel in binary form) designed by independent parties that are distributed under their own license agreements. However, FModel does not properly abide by many of the license agreements of the software that it relies upon. After a cursory glance, FModel appears to directly breach the licensing agreements of the following pieces of software, although the list is by no means exhaustive:

* **AdonisUI** - MIT (fails "this permission notice shall be included in all copies")
* **Autoupdater.NET.Official** - MIT (fails "this permission notice shall be included in all copies", notably also unmentioned in software)
* **AvalonEdit** - MIT (fails "this permission notice shall be included in all copies")
* **CSCore** - Ms-PL (fails "must retain all copyright ... notices that are present in the software")
* **DiscordRichPresence** - MIT (fails "this permission notice shall be included in all copies", notably also unmentioned in software)
* **ImGui.NET** - MIT (fails "this permission notice shall be included in all copies", notably also unmentioned in software)
* **K4os.Compression.LZ4.Streams** - MIT (fails "this permission notice shall be included in all copies")
* **Newtonsoft.Json** - MIT (fails "this permission notice shall be included in all copies")
* **NVorbis** - MIT (fails "this permission notice shall be included in all copies")
* **Oodle.NET** - MIT (fails "this permission notice shall be included in all copies", notably also unmentioned in software)
* **Ookii.Dialogs.Wpf** - BSD 3-Clause (fails "must retain the above copyright notice")
* **OpenTK** - MIT (fails "this permission notice shall be included in all copies", notably also unmentioned in software)
* **RestSharp** - Apache License 2.0 (fails "must give any other recipients of the Work or Derivative Works a copy of this License")
* **Serilog** - Apache License 2.0 (fails "must give any other recipients of the Work or Derivative Works a copy of this License")
* **SixLabors.ImageSharp** - Six Labors Split License = Apache License 2.0 (fails "must give any other recipients of the Work or Derivative Works a copy of this License", notably also unmentioned in software)
* **SkiaSharp** - MIT (fails "this permission notice shall be included in all copies", notably also unmentioned in software)
* likely even more that I did not notice after a cursory glance, such as any uncredited libraries used in CUE4Parse

Distributing these works as a part of FModel without properly following their license agreements is in direct violation of federal copyright law, and although the reverse engineering community does tend to play fast and loose with proper licensing, a project as polished as FModel needs to make a point of respecting the wishes of other open-source developers. Ideally, licensing information for currently improperly-licensed works should be included somewhere in this repository or within the software itself.

**Comment by Gteditor99** [comment]
The licenses for the third-party libraries that `FModel` relies upon are included in the respective repositories of the project,
and I have listed some here:

- [AdonisUI](https://github.com/benruehl/adonis-ui)
- [Autoupdater.NET.Official](https://github.com/ravibpatel/AutoUpdater.NET/blob/master/LICENSE)
- [AvalonEdit ](AvalonEdit)
- [CSCore](https://github.com/filoe/cscore/blob/master/license.md)
- [DiscordRichPresence](https://github.com/Lachee/discord-rpc-csharp/blob/master/LICENSE)
- [ImGui.NET](https://github.com/mellinoe/ImGui.NET/blob/master/LICENSE)
- [K4os.Compression.LZ4.Streams](https://github.com/MiloszKrajewski/K4os.Compression.LZ4/blob/master/LICENSE)
- [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json/blob/master/LICENSE.md)
- [NVorbis](https://github.com/NVorbis/NVorbis/blob/master/LICENSE)
- [Oodle.NET](https://github.com/NotOfficer/Oodle.NET/blob/master/LICENSE)
- [Ookii.Dialogues.Wpf](https://github.com/ookii-dialogs/ookii-dialogs-wpf/blob/master/LICENSE)
- [OpenTK](https://github.com/opentk/opentk#license)
- [RestSharp](https://github.com/restsharp/RestSharp#license-apache-license-20)
- [Serilog](https://github.com/serilog/serilog/blob/dev/LICENSE)
- [SixLabors.ImageSharp](https://github.com/SixLabors/ImageSharp#license)
- [SkiaSharp](https://github.com/mono/SkiaSharp/blob/main/LICENSE.md)

Consider using tools such as [`licensecheck`](https://github.com/google/licensecheck), or including a file in your repository that is separate from [`LICENSE`](https://github.com/4sval/FModel/blob/master/LICENSE) that lists all of the third-party software you use along with their respective licenses.

**Comment by 4sval** [comment]
Thank you for reporting this.
I believe that most licensing violations should be resolved at the moment, at least on FModel.
I'll be updating CUE4Parse as well when I'll be done reworking that README.
