### ISSUE TITLE
Language select isn't listing languages properly

### ISSUE THREAD

**Issue by Liggliluff** [4sval/FModel#368]
### Game

FModel

### Error

```shell
Language settings
```

### Reproduction steps

In the language select, some of the languages are available in multiple variants, but some don't have the variant specified. Sometimes the variant is improperly listed.

* English variants are listed as "Australian English, British English, English".
I assume the last one is American English, so these should rather list as "English (Australia), English (United Kingdom), English (United States)".
* Spanish lists "Español, Español (Latinoaméricano), Español (Mexicano)".
Should rather list "Español (Latinoamérica), Español (Mexico), Español (España)".
* Portuguese lists "Portugês, Portugês (Brasil)".
Should rather list "Portugês (Portugal), Portugês (Brasil)".
* Arabic, Japanese, Korean, Chinese, Traditional Chinese, Thai are weirdly also listed in English, which they shouldn't. Even more weird, Russian does not list the name in English (which it shouldn't so it is correct). Having the English name listed alongside the native name does not help native speakers at all, and if you don't know what the native name is and have to rely on the English name, then you don't speak that language. Also, it's listed just as Chinese and not Chinese (Simplified), and missing space before the parentheses, or it should use the fullwidth parentheses without a space.

**Comment by 4sval** [comment]
really?

**Comment by 4sval** [comment]
people will use common sense to understand what language they are choosing
the text between parentheses is meant to be in English for everyone to understand
and the variant chosen is game dependent, it is not representative of what will actually be loaded

**Comment by Liggliluff** [comment]
It's just ugly looking. And why do "everyone" (those who know English) need to know which is Arabic and Thai, but not know which is Russian or Dutch? Seems weird.

**Comment by 4sval** [comment]
*It's just ugly looking*
don't look at it then
