### ISSUE TITLE
Keyboard shortcut key name are inadequate

### ISSUE THREAD

**Issue by Liggliluff** [4sval/FModel#370]
### Game

FModel

### Error

```shell
Settings, keyboard shortcut key show up with their virtual key names rather than actual key names. It is great that FModel uses the virtual key codes for registering and reading keyboard shortcuts, that is how you do it on Windows. Its only issue is it showing the wrong key names.

Key names are letters A-Z and 0-9 for virtual keys A-Z and 0-9, and for all other OEM keys, the key name is the unshifted symbol. (I do wish it was the shifted symbol if the shifted symbol is the uppercase version of the unshifted symbol, see Swedish OEM_3 key with ö Ö, but that's not the standard in Windows)
```

### Reproduction steps

1. Go to Settings > Keybindings
2. Choose one option and set the key to any key that isn't A-Z, 0-9, F-keys, NumPad or the keys such as Home/End.
3. The keyname will show up as "OemSomething"

These keynames are weird for the general user, especially keys "Oem3" and "Oem6". Other key names such as "OemQuotes" and "OemQuestion" aren't at all useful since these keys do not represent quotes or question mark on a lot of keyboards.

The actual symbols that should show up when using different keyboards are as follows:
| VK code | FModel | US | UK | DE | SE |
| --- | --- | --- | --- | --- | --- |
| OEM_1 | Oem1 | ; | ; | ü | ¨ |
| OEM_2 | OemQuestion | / | / | # | ' |
| OEM_3 | Oem3 | \` | ' | ö | ö |
| OEM_4 | OemOpenBrackets | [ | [ | ß | ´ |
| OEM_5 | Oem5 | \\ | \\ | ^ | § |
| OEM_6 | Oem6 | ] | ] | ´ | å |
| OEM_7 | OemQuotes | ' | # | ä | ä |
| OEM_8 | Oem8 |  | \` |   |   |
| OEM_COMMA | OemComma | , | , | , | , |
| OEM_PERIOD | OemPeriod | . | . | . | . |
| OEM_MINUS | OemMinus | - | - | - | - |
| OEM_PLUS | OemPlus | = | = | + | + |
| OEM_102 | OemBackslash | \\ |  | < | < |

**Comment by 4sval** [comment]
nobody cares
go use ChatGPT somewhere else kthx
