### ISSUE TITLE
Unable to extract meshes.

### ISSUE THREAD

**Issue by IOHunter98** [4sval/FModel#373]
Decided to post my issue here, as my previous report in the official Discord server had disappeared without notice. Here is a copypasta of my issue:

**Game**: Fortnite
**UE Version**: 4.26
**AES Key**: 0x44034A9FFA18B1BF680B3BD22784CDCDA76B8A0CF1F2DD333FA0B7C0A5BD92A0

**Error Description**: Unable to save meshes (Static Meshes - .psk) in the latest release of FModel (Beta - v4.4.2.0). I am attempting to extract some meshes from the builds v15.30 and v20.40 for a project. This error does not occur elsewhere and I am able to extract other things such as audio and PNG textures normally. In addition, the model viewer does not work either. The error reads: "[WRN] Could not save 'STATIC MESH'". I have the right Paks directory, the needed Microsoft Redistributable, and the mandatory Microsoft .NETs. I also have all the AES keys correctly implemented,  I have the mapping file (.usmap) for each respective version via local and correct Unreal Versions selected for each build (UE4_26 for v15.30, UE5_0 for v20.40).  The provided screenshots show the issue for v15.30. Assistance would be greatly appreciated, thank you!
 
**Reproduction Steps**:
`1.` Opened FModel (as administrator) and checked the settings to ensure all is correct.
`2.` Checked the AES keys.
`3.` Loaded all Archives.
`4.` Located and attempted to extract the meshes as .psk.
`5.` Error occurs. [WRN] Could not save 'STATIC MESH'.
![fmodelnoextract1](https://user-images.githubusercontent.com/128950535/227754364-be5eb91f-ef6c-44a0-849a-cd7515401c6c.png)
![fmodelnoextract2settings](https://user-images.githubusercontent.com/128950535/227754366-e14515b0-674e-4a35-acd7-a41def5bf5ab.png)
![fmodelnoextract3aesmanager](https://user-images.githubusercontent.com/128950535/227754370-659a73d3-0ffc-4bbc-9702-88d5f3fab6ed.png)

**Comment by Amrsatrio** [comment]
Where did you get the 15.30 mappings from? Did you dump it yourself?
