### ISSUE TITLE
Unable to find oo2core_9_win64.dll

### ISSUE THREAD

**Issue by Beat-YT** [4sval/FModel#374]
### Game

Fortnite

### Error

```shell
An unhandled exception occurred: Unable to load DLL 'C: \Users\username\Downloads\Model\Output\data loo2core 9 win64.dll' or one of its dependencies: Le module spécifié est introuvable. (0x8007007E)
```

### Reproduction steps

1. Use manifest LIVE 
2. Error happens

**Comment by Beat-YT** [comment]
Bro what

**Comment by Beat-YT** [comment]
![IMG_20230326_183254__01](https://user-images.githubusercontent.com/66485277/227808881-6f2a5087-fa0e-401a-bdf2-0b25dc24439d.jpg)

**Comment by Beat-YT** [comment]
@4sval ??

**Comment by lkxoayh** [comment]
supprime fmodel dans le appdata etc et delete pour les files pouvont etre relier a fmodel et re installe et normalement sa marche

**Comment by MasterCATZ** [comment]
what reinstall? its just a zip file with FModel.exe inside ?
