### ISSUE TITLE
umap model exporter

### ISSUE THREAD

**Issue by jkerman2000** [4sval/FModel#375]
### Description

I would like to be able to export an entire umap file as a model from the 3d viewer. I'm trying to reconstruct maps in Blender one mesh at a time and it's unbelievably tedious. If all the meshes could be combined into a single file, it would save a huge amount of time.

**Comment by 4sval** [comment]
https://github.com/MinshuG/BlenderUmap2

**Comment by jkerman2000** [comment]
> https://github.com/MinshuG/BlenderUmap2

I tried to build that addon and kept getting errors. I have no idea what I'm doing, sorry.
