### ISSUE TITLE
Class name (and DataTable) deserialisation issues for PUBG: Battlegrounds v23.1+

### ISSUE THREAD

**Issue by eebAlt** [4sval/FModel#379]
### Game

PUBG: Battlegrounds (currently just Test Server; the update will be pushed to prod on the 12th)

### Error

In most cases the issue gives no error message in the log, but attempting to read a DataTable produces the following (and fails to read the table's rows):

```shell
2023-04-05 12:59:39 [FModel] [ERR] Could not read DataTable correctly
System.NullReferenceException: Object reference not set to an instance of an object.
   at CUE4Parse.UE4.Assets.Exports.Engine.UDataTable.Deserialize(FAssetArchive Ar, Int64 validPos)
   at CUE4Parse.UE4.Assets.AbstractUePackage.DeserializeObject(UObject obj, FAssetArchive Ar, Int64 serialSize)
```

### Reproduction steps

1. Load the game archives of PUBG: Test Server (as GAME_PlayerUnknownsBattlegrounds).
2. Attempt to open a DataTable asset (e.g. `TslGame/Content/DesignData/Bluezone/Bluezone_Erangel_old.uasset`); the `RowStruct` property will be named `*72ed7d5fe2` instead, and the table's rows will not be output.
3. Alternatively, many other files are also displaying similar deserialisation issues (e.g. `TslGame/Content/Blueprints/BP_DefaultTslSingleton.uasset`), with many property keys and non-default class names replaced with strings similar to `*9e6bab664f`.

Log file: [FModel-Log-2023-04-05.txt](https://github.com/4sval/FModel/files/11158499/FModel-Log-2023-04-05.txt)

**Comment by LongerWarrior** [comment]
They hashed a bunch of FNames to the strings like these `*72ed7d5fe2` so unless there will be some sort of dictionary for these it will fail to parse some assets
