### ISSUE TITLE
Bug Title

### ISSUE THREAD

**Issue by muslimcyber26** [4sval/FModel#386]
### Game

Mail Time

### Error

```shell
I want to see and extracting for that game. Btw, game using the Unreal 5. Cause inside paks folder contains "Paks, Utoc, Ucas, Sig". The archive have a AES key. But, after get the Aes Key using tools from Spiritvoid. And put the AES key in FMODEL. And then FMODEL Get Error like this:

[ERR] System.Collections.Generic.KeyNotFoundException: Couldn't find chunk 0x00000000 | 5 in IoStore global.utoc
   at CUE4Parse.UE4.IO.IoStoreReader.Read(FIoChunkId chunkId)
```

### Reproduction steps

1. Load the Archive and selecting folder contains paks "MailTime\MailTime\Content\Paks"
2. Load the AES Key
3. And get this Error:
4. `[ERR] System.Collections.Generic.KeyNotFoundException: Couldn't find chunk 0x00000000 | 5 in IoStore global.utoc
   at CUE4Parse.UE4.IO.IoStoreReader.Read(FIoChunkId chunkId)`

This log files [FModel-Log-2023-05-10.txt](https://github.com/4sval/FModel/files/11441039/FModel-Log-2023-05-10.txt)

**Comment by 4sval** [comment]
> game using the Unreal 5. Cause inside paks folder contains "Paks, Utoc, Ucas, Sig"

no
use the correct ue version
