### ISSUE TITLE
Fatale error

### ISSUE THREAD

**Issue by Tavish-153** [4sval/FModel#395]
### Game

The Whold Client

### Error

```shell
It didn't generate a log
```

### Reproduction steps

1. Just Open the App

**Comment by Tavish-153** [comment]
When i try To open it, It Just says Fatal error with 3 options 1 Reset Settings 2 Restart 3 Ok

**Comment by 4sval** [comment]
Send the log file please

**Comment by Tavish-153** [comment]
> Send the log file please

It worked i just had to delete the settings json
