### ISSUE TITLE
S.T.A.L.K.E.R. 2 not worked!

### ISSUE THREAD

**Issue by ponaromixxx** [4sval/FModel#396]
Does not open files from the developer version, possibly a different format.
KEY AES:  0x33A604DF49A07FFD4A4C919962161F5C35A134D37EFA98DB37A34F6450D7D386
KEY Base64:  M6YE30mgf/1KTJGZYhYfXDWhNNN++pjbN6NPZFDX04Y=

**Comment by GMatrixGames** [comment]
https://github.com/FModel/Game-Compatibility/blob/master/TESTED_BUT_BROKEN.md#unreal-engine-50

**Comment by bronxyx** [comment]
sup
