### ISSUE TITLE
I keep getting an error at the output of FModel: "System.IndexOutOfRangeException: Index was outside the bounds of the array."

### ISSUE THREAD

**Issue by Speedymario** [4sval/FModel#397]
### Description

After loading every package from Fortnite, with the correct and updated AES keys, and with the .NET required version, they load correctly. The issue is when I try to hear a sound, see a model, or anything. I keep getting in the output:
[ERR] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at CUE4Parse.UE4.Readers.FByteArchive.ReadArray(Int32 length)
![imagen_2023-06-17_031809410](https://github.com/4sval/FModel/assets/88109678/9722b850-d42a-4db1-8d6b-726b85096ea6)
![imagen_2023-06-17_031822831](https://github.com/4sval/FModel/assets/88109678/306522ff-9443-42c3-92ee-5fad76db0cfd)
I tried to look on youtube for the issue but nothing related with FModel appeared. I tried reinstalling the program following the instructions step by step, even reinstalling .NET required version, but nothing didn't work.

**Comment by 4sval** [comment]
use the correct ue version
