### ISSUE TITLE
Package has unversioned properties - FModel trying to load UE5 as UE4

### ISSUE THREAD

**Issue by MonsterDruide1** [4sval/FModel#398]
### Game

Satisfactory Experimental

### Error

```
[ERR] CUE4Parse.UE4.Exceptions.ParserException: Package has unversioned properties but mapping file is missing, can't serialize
   at CUE4Parse.UE4.Assets.Package..ctor(FArchive uasset, FArchive uexp, Lazy`1 ubulk, Lazy`1 uptnl, IFileProvider provider, TypeMappings mappings, Boolean useLazySerialization)
```
This error happens when opening basically any non-trivial file (uasset, umap).
I've set the UE version to `GAME_UE5_1` in the settings, but the error message still says something about loading from UE4... that's where I suspect the issue.

Satisfactory recently upgraded from UE4 to UE5, and the main game binary has the version description `5.1.1.0`, so I selected `UE5_1` accordingly. Maybe I've also drawn a wrong conclusion here, although from my experience that version has always matched the UE version.

### Reproduction steps

1. Switch to Satisfactory Experimental in the Steam Configs
2. Open its folder and main package in FModel
3. Try opening for example `FactoryGame/Content/BTD_DistanceCheck.uasset`
4. Observe the error message

**Comment by 4sval** [comment]
Q: ***"Package has unversioned properties but mapping file is missing, can't serialize"***
A: Generate the appropriate mapping file for the version of the game you load in FModel. You can then set the mapping file in the settings.
https://github.com/OutTheShade/UnrealMappingsDumper


https://cdn.discordapp.com/attachments/637265123144237063/1119349328620830770/FactoryGame.usmap
