### ISSUE TITLE
Cant export anything from VALORANT

### ISSUE THREAD

**Issue by jasmurbtw** [4sval/FModel#399]
### Game

VALORANT

### Error

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at FModel.ViewModels.CUE4ParseViewModel.Extract(CancellationToken cancellationToken, String fullPath, Boolean addNewTab, EBulkType bulk)
```

### Reproduction steps

1. I run Fmodel ( 4.4.3.2 )
2. I'm trying to export animations ( any of them. For example "ShooterGame>Content>Equippables>Melee>S0>1P>Anims>EQ_Core_Melee_Karambit_S0_Attack1" ) and I'm getting an error. Same error when im trying to export textures or models.

**Comment by 4sval** [comment]
use the correct ue version
