### ISSUE TITLE
Snowbreak Containment Zone meshes fail to load

### ISSUE THREAD

**Issue by ThiconZ** [4sval/FModel#409]
### Game

Snowbreak Containment Zone

### Error

```shell
No error/warning/log output appears in FModel. When running from source under VS the following appears in Output as the model renderer window appears:
Projection (1): InvalidEnum
```

### Reproduction steps

1. Open a Snowbreak PAK file such as PAK_Game_Characters_27-WindowsNoEditor.pak
2. Browse to a mesh such as Game\Content\Characters\Girl\girl001\girl001_body01_skm.uasset
3. Attempt to open the model for viewing in FModel
4. Observe no model appears

![image](https://github.com/4sval/FModel/assets/6924950/ba8591b6-d381-414e-ba77-cadf826528a0)
![image](https://github.com/4sval/FModel/assets/6924950/fb550540-c597-442a-8cad-44f53af8117d)

Game website for reference: https://snowbreak.amazingseasun.com/#/en?id=1
This is using the PC version of the game and not the mobile version.

Additional Note: Attempting to export a model to GLTF throws an error from [CUE4Parse-Conversion\Meshes\Gltf.cs Line 80](https://github.com/FabianFG/CUE4Parse/blob/2cdf9d61e66253f746f6a6e5b23b57979fbaab69/CUE4Parse-Conversion/Meshes/Gltf.cs#L80). However changing the line to the following will resolve that:
`mesh.Extras = morphTargets.Length > 0 ? JsonContent.Parse(targetNames) : null;`

**Comment by 4sval** [comment]
pull cue4parse

**Comment by ThiconZ** [comment]
> pull cue4parse

Making that change to CUE4Parse that I mentioned does not fix the rendering problem. That is purely for getting FModel to allow _exporting_ to GLTF.

**Comment by 4sval** [comment]
the rendering problem is caused by this game having "Game" as its internal game name and it's been fixed [3 weeks ago](https://github.com/FabianFG/CUE4Parse/commit/50cf8823d631f54c138ee296d09b23783402ec5e)

**Comment by 4sval** [comment]
what error does it throw when exporting to GLTF?
cause JsonContent.Parse takes a valid JSON string even if there are no morph targets

**Comment by 4sval** [comment]
actually it might be just caused by the internal game name again

**Comment by ThiconZ** [comment]
I created a PR in CUE4Parse with some extra details on the issue: https://github.com/FabianFG/CUE4Parse/pull/99

The exception is: `reference not set to an instance of an object.`

**Comment by ThiconZ** [comment]
> actually it might be just caused by the internal game name again

I switched over to the FModel dev branch and master branch of CUE4Parse and the model rendering is fixed. The export error still happens without my PR though.
![image](https://github.com/4sval/FModel/assets/6924950/d3bed72a-98e3-4f5d-9f62-4ad45a69b519)
