### ISSUE TITLE
Bug Title

### ISSUE THREAD

**Issue by Talulaxxx** [4sval/FModel#412]
### Game

hogwarts legacy

### Error

```shell
Nothing, the application simply closes when I try to extract an INT file in Json
```

### Reproduction steps

The application simply closes when I try to extract an INT file in Json. <<<

FModel simply closes every time I try to extract the INT file. For example, I tried to extract the "Ollivanders" store. I selected the files mentioned in the video, managed to extract them all separately, just to find which one was the real problem. I really don't know what to do to fix this. My problem is the INT file itself :c

**Comment by 4sval** [comment]
use the correct ue version
