### ISSUE TITLE
Previews are not loaded

### ISSUE THREAD

**Issue by GamesLuke** [4sval/FModel#415]
### Game

Fortnite

### Error

```shell
The previews are shown only with the writings and the placeholder one comes out as the image due to the absence of images

Please fix it quickly because next season is Friday and I wanted to leak something
```

### Reproduction steps

Quite simply I went to cosmetics and it doesn't load the previews
(I use the beta version because the stable one doesn't load)
https://github.com/4sval/FModel/assets/127786942/3fae4033-6421-4439-9e87-ca71e0c8664a
(I also checked the AES keys)

**Comment by GhostScissors** [comment]
![image](https://github.com/4sval/FModel/assets/79089473/cf3755d0-49fc-4583-b754-98c8121a3269)

**Comment by 4sval** [comment]
You want to leak, I want you to not leak, won't be fixed.
