### ISSUE TITLE
Remnant 2 Unable to read Audio files

### ISSUE THREAD

**Issue by Korbelly** [4sval/FModel#416]
### Game

Remnant 2

### Error

```shell
[ERR] System.OverflowException: Arithmetic operation resulted in an overflow.
   at CUE4Parse.UE4.Readers.FByteArchive.ReadArray(Int32 length)
```

### Reproduction steps

1. Select GAME_UE5_2 as the UE Version in the settings
2. Load Remnant 2
3. Enter the AES Key
4. Open any audio file

**Comment by Korbelly** [comment]
Game uses UE 5.2

**Comment by GhostScissors** [comment]
Use mappings https://discord.com/channels/637265123144237061/1137496366369734696/1137496494090502164

**Comment by 4sval** [comment]
build fmodel dev from source
